from importlib import _bootstrap_external
from importlib import _bootstrap_external
import sys

file = '/Users/basmalh/Downloads/abaar/abeer-aldhiafah-pro-en.html'
with open(file, 'r', encoding='utf-8') as f:
    html = f.read()

# Update lang and dir
html = html.replace('<html lang="ar" dir="rtl">', '<html lang="en" dir="ltr">')

# Translate all major strings
translations = {
    'شركة عبير الضيافة للنقليات': 'Abeer Aldhiafah Transport',
    'شركة عبير الضيافة': 'Abeer Aldhiafah',
    'عبير الضيافة': 'Abeer Aldhiafah',
    'للنقليات · Abeer Aldhiafah': 'Transport · Abeer Aldhiafah',
    'من نحن': 'About Us',
    'خدماتنا': 'Our Services',
    'لماذا نحن': 'Why Choose Us',
    'التغطية': 'Coverage',
    'مناطق التغطية': 'Coverage Areas',
    'الأسعار': 'Pricing',
    'تواصل': 'Contact',
    'تواصل معنا': 'Contact Us',
    'احجز الآن': 'Book Now',
    'احجز عبر واتساب': 'Book via WhatsApp',
    'رحلة مريحة<br>بخدمة <em>راقية</em>': 'Comfortable Journey<br>With <em>Premium</em> Service',
    'نقدم خدمات النقل والضيافة بأعلى معايير الجودة لنضمن لكم رحلة آمنة ومريحة وتجربة لا تُنسى.': 'We provide transport and hospitality services with the highest quality standards to ensure a safe, comfortable, and unforgettable journey.',
    'تواصل واتساب': 'WhatsApp Us',
    'أمان': 'Safety',
    'سلامتك هي أولويتنا': 'Your safety is our priority',
    'راحة': 'Comfort',
    'مقاعد مريحة ومساحات واسعة': 'Comfortable seats and spacious areas',
    'التزام': 'Commitment',
    'الالتزام بالمواعيد بدقة': 'Strict punctuality',
    'خدمة عملاء': 'Customer Support',
    'دعم على مدار الساعة': '24/7 Support',
    'منطقة مغطاة': 'Covered Areas',
    'خدمات متكاملة': 'Integrated Services',
    'خدمة متواصلة': 'Continuous Service',
    'أسطول حافلات': 'Bus Fleet',
    'مرن': 'Flexible',
    'تسعير حسب البرنامج': 'Custom Pricing',
    'حديث': 'Modern',
    'أسطول نقل متكامل': 'Integrated Transport Fleet',
    'نمتلك أسطولاً من الحافلات الكبيرة الحديثة، مجهزة لأعلى معايير الراحة والسلامة، تغطي جميع مناطق المملكة في خدمة ضيوف الرحمن وزوار الأماكن المقدسة.': 'We own a fleet of modern large buses, equipped with the highest standards of comfort and safety, covering all regions of the Kingdom to serve pilgrims and visitors to the holy sites.',
    'مكة المكرمة': 'Mecca',
    'الرصيفة - مجمع الجروشي مول - مكتب 25': 'Al-Rusaifah - Al-Jaroushi Mall - Office 25',
    'شركة ضيافة ونقل بمعايير عالمية': 'Hospitality & Transport with Global Standards',
    'شركة عبير الضيافة للنقليات شركة سعودية متخصصة في تقديم خدمات النقل والعمرة والإعاشة داخل جميع مناطق المملكة العربية السعودية، بأسطول حديث ومعايير تشغيل عالية تضمن الجودة والالتزام وراحة العملاء.': 'Abeer Aldhiafah Transport is a Saudi company specialized in providing transport, Umrah, and catering services across all regions of Saudi Arabia, with a modern fleet and high operating standards that ensure quality, commitment, and customer comfort.',
    'نعمل على تصميم برامج نقل مرنة تناسب احتياجات الأفراد والمجموعات، مع اهتمام دقيق بأدق تفاصيل الرحلة لضمان تجربة مريحة وآمنة لجميع ضيوف الرحمن.': 'We design flexible transport programs that suit the needs of individuals and groups, paying close attention to every detail of the journey to ensure a comfortable and safe experience for all pilgrims.',
    'معايير جودة عالية': 'High Quality Standards',
    'التزام تام': 'Full Commitment',
    'برامج مرنة': 'Flexible Programs',
    'خبرة موسمية': 'Seasonal Experience',
    'تغطية شاملة': 'Comprehensive Coverage',
    'ما نقدمه لكم': 'What We Offer',
    'نرتقي بخدمات النقل والضيافة لنمنحكم تجربة مريحة وآمنة في رحلاتكم الدينية والسياحية': 'We elevate transport and hospitality services to give you a comfortable and safe experience in your religious and tourist trips.',
    'خدمة العمرة': 'Umrah Service',
    'برامج عمرة متكاملة مصممة بعناية لتمنحكم تجربة روحانية استثنائية بأعلى معايير الراحة والأمان.': 'Carefully designed integrated Umrah programs to give you an exceptional spiritual experience with the highest standards of comfort and safety.',
    'برامج عمرة فردية وجماعية': 'Individual & Group Umrah Programs',
    'نقل من وإلى الحرم المكي': 'Transport to & from the Grand Mosque',
    'تنسيق كامل لتفاصيل الرحلة': 'Full coordination of trip details',
    'برامج موسمية متجددة': 'Renewed seasonal programs',
    'متابعة ميدانية مستمرة': 'Continuous field follow-up',
    'متاح طوال العام': 'Available Year-Round',
    'خدمات النقل': 'Transport Services',
    'أسطول حديث من الحافلات الكبيرة يغطي جميع مناطق المملكة بأعلى مستويات الراحة والسلامة.': 'A modern fleet of large buses covering all regions of the Kingdom with the highest levels of comfort and safety.',
    'حافلات كبيرة حديثة المواصفات': 'Modern large buses',
    'تغطية جميع مناطق المملكة': 'Covering all regions of Saudi Arabia',
    'نقل الأفراد والمجموعات الكبيرة': 'Transporting individuals & large groups',
    'سائقون محترفون مرخصون': 'Professional licensed drivers',
    'جداول منظمة وثابتة': 'Organized and fixed schedules',
    'جميع مناطق المملكة': 'All Kingdom Regions',
    'خدمات الإعاشة': 'Catering Services',
    'حلول إقامة وإعاشة متكاملة تضمن راحتكم وسلامتكم طوال فترة إقامتكم في أي منطقة بالمملكة.': 'Integrated accommodation and catering solutions that ensure your comfort and safety during your stay in any region of the Kingdom.',
    'حلول إقامة متنوعة ومرنة': 'Diverse and flexible accommodation',
    'خدمات تموين ووجبات': 'Catering and meal services',
    'إعاشة للمجموعات الكبيرة': 'Catering for large groups',
    'برامج موسم الحج والعمرة': 'Hajj and Umrah season programs',
    'تنسيق كامل مع شركاء الخدمة': 'Full coordination with service partners',
    'حسب الطلب والميزانية': 'According to request & budget',
    'ما يميزنا عن غيرنا': 'What Sets Us Apart',
    'نؤمن بأن التفاصيل الصغيرة تصنع الفرق الكبير في تجربتكم': 'We believe that small details make a big difference in your experience',
    'جودة لا تُساوم': 'Uncompromised Quality',
    'نلتزم بأعلى معايير الجودة في جميع خدماتنا ونخضع لمراجعة مستمرة لضمان الأفضل لكم': 'We adhere to the highest quality standards in all our services and undergo continuous review to ensure the best for you.',
    'حافلات كبيرة حديثة مجهزة بأحدث وسائل الراحة والسلامة، خضعت لجميع الاشتراطات الرسمية': 'Modern large buses equipped with the latest comfort and safety features, compliant with all official requirements.',
    'نغطي جميع مناطق المملكة العربية السعودية الثلاث عشرة بكفاءة عالية وتنسيق احترافي': 'We cover all 13 regions of Saudi Arabia with high efficiency and professional coordination.',
    'الالتزام بالمواعيد': 'Punctuality',
    'الوقت ثمين خاصة في رحلات العمرة والحج، نلتزم بدقة بالمواعيد المتفق عليها في جميع الأحوال': 'Time is precious, especially during Umrah and Hajj trips. We strictly adhere to agreed-upon schedules under all circumstances.',
    'تغطية شاملة لجميع أرجاء المملكة': 'Comprehensive Coverage Across the Kingdom',
    'نفخر بتقديم خدماتنا في جميع المناطق الثلاث عشرة للمملكة العربية السعودية بأسطول حافلات كبيرة وحديثة وسائقين محترفين': 'We are proud to provide our services in all 13 regions of Saudi Arabia with a modern fleet of large buses and professional drivers.',
    'المدينة المنورة': 'Medina',
    'الرياض': 'Riyadh',
    'جدة': 'Jeddah',
    'الطائف': 'Taif',
    'الدمام': 'Dammam',
    'الجبيل': 'Jubail',
    'أبها': 'Abha',
    'تبوك': 'Tabuk',
    'حائل': 'Hail',
    'القصيم': 'Qassim',
    'جازان': 'Jazan',
    'نجران': 'Najran',
    'الباحة': 'Al Baha',
    'وجميع مناطق المملكة ✦': 'And all regions of the Kingdom ✦',
    'برامجنا': 'Our Programs',
    'برامج متخصصة لكل موسم': 'Specialized Programs for Every Season',
    'نصمم برامج متكاملة مرنة تتناسب مع كل موسم واحتياج': 'We design flexible, integrated programs tailored to every season and need.',
    'موسم العمرة': 'Umrah Season',
    'طوال العام - رمضان وغيره': 'Year-Round - Ramadan and beyond',
    'نقل مريح من وإلى الحرم': 'Comfortable transport to/from the Haram',
    'برامج رمضان المتخصصة': 'Specialized Ramadan programs',
    'أسعار تنافسية حسب الموسم': 'Competitive seasonal prices',
    'موسم الحج': 'Hajj Season',
    'ذو الحجة - الأيام المباركة': 'Dhul Hijjah - The Blessed Days',
    'نقل ضيوف الرحمن لجميع المشاعر': 'Transporting pilgrims to all holy sites',
    'تنسيق إعاشة كاملة في مكة': 'Full catering coordination in Mecca',
    'تشغيل على مدار الساعة': 'Round-the-clock operations',
    'طواقم متخصصة وذات خبرة': 'Specialized and experienced crews',
    'برامج مجموعات منظمة': 'Organized group programs',
    'السياحة والنقل العام': 'Tourism & Public Transport',
    'طوال العام - جميع مناطق المملكة': 'Year-Round - All Kingdom Regions',
    'نقل بين المدن والمناطق': 'Intercity and regional transport',
    'رحلات سياحية منظمة': 'Organized tourist trips',
    'تأجير حافلات بسائق': 'Bus rental with a driver',
    'نقل المجموعات المؤسسية': 'Corporate group transport',
    'برامج مرنة حسب الطلب': 'Flexible custom programs',
    'آراء العملاء': 'Client Reviews',
    'ماذا يقول عملاؤنا': 'What Our Clients Say',
    'ثقة عملائنا هي أعظم شهادة لجودة خدماتنا': 'Our clients\' trust is the greatest testament to the quality of our services.',
    'تجربة ممتازة مع شركة عبير الضيافة في موسم العمرة، الحافلات نظيفة ومريحة جداً والسائق محترف ومنظم. سنكرر التجربة بإذن الله.': 'An excellent experience with Abeer Aldhiafah during the Umrah season. The buses are very clean and comfortable, and the driver is professional and organized. We will definitely repeat the experience.',
    'محمد أحمد': 'Mohammed Ahmed',
    'رحلة عمرة - الرياض': 'Umrah Trip - Riyadh',
    'نظمنا رحلة جماعية لمجموعة كبيرة وكانت الخدمة احترافية جداً. الالتزام بالمواعيد والتنسيق الرائع جعل رحلتنا لا تُنسى. شكراً عبير الضيافة.': 'We organized a group trip, and the service was very professional. Punctuality and excellent coordination made our trip unforgettable. Thank you, Abeer Aldhiafah.',
    'فاطمة السالم': 'Fatima Al-Salem',
    'رحلة جماعية - جدة': 'Group Trip - Jeddah',
    'خدمة النقل في موسم الحج كانت استثنائية، التزام تام بالمواعيد والتوجيه الدقيق لجميع المشاعر المقدسة. أنصح بهم بشدة لجميع الحجاج.': 'Transport service during Hajj was exceptional. Strict punctuality and precise routing to all holy sites. I highly recommend them to all pilgrims.',
    'عبدالله المطيري': 'Abdullah Al-Mutairi',
    'موسم الحج - المدينة': 'Hajj Season - Medina',
    'أسعار مرنة تناسبكم': 'Flexible Pricing for You',
    'سعر مخصص لكل برنامج': 'Custom Price for Each Program',
    'نؤمن بأن لكل رحلة متطلباتها الخاصة، لذلك نصمم الأسعار بمرونة تامة تتناسب مع نوع البرنامج والموسم وعدد المشاركين والمسافة. تواصلوا معنا للحصول على عرض سعر مخصص مجاناً.': 'We believe every trip has its specific requirements. That\'s why we design flexible pricing based on the program type, season, number of participants, and distance. Contact us for a free custom quote.',
    'حسب الموسم': 'By Season',
    'حسب العدد': 'By Group Size',
    'حسب البرنامج': 'By Program',
    'حسب المسافة': 'By Distance',
    'احصل على عرض سعر مجاني': 'Get a Free Quote',
    'نحن هنا لخدمتكم': 'We Are Here to Serve You',
    'فريقنا المتخصص متاح للإجابة على جميع استفساراتكم وتصميم البرنامج الأمثل الذي يناسب احتياجاتكم وميزانيتكم. تواصلوا معنا عبر أي وسيلة تناسبكم.': 'Our dedicated team is available to answer all your inquiries and design the optimal program that fits your needs and budget. Contact us through any method you prefer.',
    'الهاتف': 'Phone',
    'واتساب': 'WhatsApp',
    'البريد الإلكتروني': 'Email',
    'انستجرام': 'Instagram',
    'الموقع': 'Location',
    'احجز الآن عبر واتساب': 'Book Now via WhatsApp',
    'تواصل مباشرة مع فريقنا المتخصص وسنقوم بتصميم البرنامج المثالي الذي يناسب احتياجاتك في أقل من 24 ساعة': 'Communicate directly with our specialized team, and we will design the perfect program for your needs in less than 24 hours.',
    'ابدأ المحادثة الآن': 'Start Chat Now',
    'متاحون 24 ساعة طوال أيام الأسبوع': 'Available 24/7 all week long',
    'موقعنا الجغرافي': 'Our Geographical Location',
    'مكة المكرمة - الرصيفة<br><strong>مجمع الجروشي مول - مكتب 25</strong>': 'Mecca - Al-Rusaifah<br><strong>Al-Jaroushi Mall - Office 25</strong>',
    'شركة سعودية متخصصة في تقديم خدمات النقل والعمرة والإعاشة داخل جميع مناطق المملكة العربية السعودية بأعلى معايير الجودة والالتزام لخدمة ضيوف الرحمن.': 'A Saudi company specialized in providing transport, Umrah, and catering services across all regions of Saudi Arabia with the highest standards of quality and commitment to serve pilgrims.',
    'روابط سريعة': 'Quick Links',
    'جميع الحقوق محفوظة': 'All rights reserved',
    '>ع<': '>AR<',
    'ABEER': 'ABEER',
    'abeer-aldhiafah-pro-en.html': 'index.html',
    'EN <i class=\\'bx bx-globe\\'></i>': 'AR <i class=\\'bx bx-globe\\'></i>',
    'English <i class=\\'bx bx-globe\\'></i>': 'العربية <i class=\\'bx bx-globe\\'></i>'
}

for ar, en in translations.items():
    html = html.replace(ar, en)

with open(file, 'w', encoding='utf-8') as f:
    f.write(html)
